# docker-compose.yml
version: '3.6'
services:
  test-db:
    image: postgres # use latest official postgres version
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - 5432:5432
