export const TEMPLATE_SERVICE = 'TEMPLATE_SERVICE';
export const TEMPLATE_HOSTNAME = 'TEMPLATE_HOSTNAME';
export const TEMPLATE_HTTP_PORT = 'TEMPLATE_HTTP_PORT';
export const TEMPLATE_TCP_PORT = 'TEMPLATE_TCP_PORT';
export const TEMPLATE_RMQ_PORT = 'TEMPLATE_RMQ_PORT';

export const BASE = 'receipt';
export const VERSION = 2;
