# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing

on:
  push:
    branches: [ feature/*, bug/*, hotfix/* ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN -g
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: yarn
    - run: yarn test --passWithNoTests
